-- =============================================================================
-- V1: criação do banco conforme o mapeamento JPA (herança JOINED e relacionamentos)
-- =============================================================================

-- Cria a tabela-pai users, com autenticação, discriminador de perfil e dados comuns da herança JOINED (Admin e Customer)
CREATE TABLE users (
    profile VARCHAR(31) NOT NULL CHECK (profile IN ('ADMIN', 'CUSTOMER')),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    active BOOLEAN NOT NULL,
    email VARCHAR(512) NOT NULL UNIQUE,
    email_lookup_hash VARCHAR(64) UNIQUE,
    my_referral_code VARCHAR(255) UNIQUE,
    password VARCHAR(255) NOT NULL,
    points INTEGER,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- Cria a tabela admin, especialização de User (JOINED) com o nome do administrador e a mesma chave de users
CREATE TABLE admin (
    name VARCHAR(512) NOT NULL,
    id BIGINT NOT NULL,
    CONSTRAINT pk_admin PRIMARY KEY (id)
);

-- Liga cada administrador ao registro correspondente em users, compartilhando o id da herança JOINED
ALTER TABLE admin
    ADD CONSTRAINT fk_admin_user
    FOREIGN KEY (id) REFERENCES users (id);

-- Cria a tabela customer, especialização de User (JOINED) com nome, telefone, endereço e data de nascimento do cliente
CREATE TABLE customer (
    address VARCHAR(512) NOT NULL,
    birth_date DATE NOT NULL,
    name VARCHAR(512) NOT NULL,
    phone VARCHAR(512) NOT NULL,
    id BIGINT NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

-- Liga cada cliente ao registro correspondente em users, compartilhando o id da herança JOINED
ALTER TABLE customer
    ADD CONSTRAINT fk_customer_user
    FOREIGN KEY (id) REFERENCES users (id);

-- Cria a tabela scheduling para o agendamento único do cliente (tipo, data e status)
CREATE TABLE scheduling (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    scheduling_date TIMESTAMP(6) NOT NULL,
    scheduling_type ENUM ('CONSULTA', 'LIMPEZA', 'MANUTENCAO'),
    status ENUM ('CANCELADO', 'CONCLUIDO', 'PENDENTE'),
    customer_id BIGINT UNIQUE,
    CONSTRAINT pk_scheduling PRIMARY KEY (id)
);

-- Relaciona o agendamento ao cliente em cardinalidade um-para-um (Customer.scheduling)
ALTER TABLE scheduling
    ADD CONSTRAINT fk_scheduling_customer
    FOREIGN KEY (customer_id) REFERENCES customer (id);

-- Cria a tabela occurrence para registrar ocorrências enviadas pelo cliente (descrição, data e categoria)
CREATE TABLE occurrence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    category VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    sent_at TIMESTAMP(6) NOT NULL,
    customer_id BIGINT,
    CONSTRAINT pk_occurrence PRIMARY KEY (id)
);

-- Relaciona cada ocorrência ao cliente em cardinalidade um-para-muitos (Customer.occurrences)
ALTER TABLE occurrence
    ADD CONSTRAINT fk_occurrence_customer
    FOREIGN KEY (customer_id) REFERENCES customer (id);

-- Cria a tabela de pedidos do cliente (nome, status e data); o identificador order é reservado e precisa de aspas
CREATE TABLE `order` (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_status ENUM ('CONCLUIDO', 'EM_ANDAMENTO', 'REALIZADO') NOT NULL,
    name VARCHAR(255) NOT NULL,
    order_date TIMESTAMP(6) NOT NULL,
    customer_id BIGINT NOT NULL,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

-- Relaciona cada pedido ao cliente em cardinalidade um-para-muitos (Customer.orders)
ALTER TABLE `order`
    ADD CONSTRAINT fk_order_customer
    FOREIGN KEY (customer_id) REFERENCES customer (id);

-- Cria a tabela available_slot para horários disponíveis de agendamento, sem vínculo com outras entidades
CREATE TABLE available_slot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    slot_date TIMESTAMP(6) NOT NULL UNIQUE,
    CONSTRAINT pk_available_slot PRIMARY KEY (id)
);

-- Cria a tabela message_template para modelos de mensagem por tipo, com referência opcional ao cliente em coluna simples
CREATE TABLE message_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT,
    template_text VARCHAR(1024) NOT NULL,
    type ENUM (
        'ANIVERSARIO',
        'COMPRA',
        'LEMBRETE_15_DIAS',
        'LEMBRETE_180_DIAS',
        'LEMBRETE_30_DIAS',
        'LEMBRETE_365_DIAS',
        'LEMBRETE_90_DIAS'
    ) NOT NULL UNIQUE,
    CONSTRAINT pk_message_template PRIMARY KEY (id)
);
