FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm install

COPY . .

EXPOSE 8081

ENV EXPO_NO_TELEMETRY=1

CMD ["npx", "expo", "start", "--host", "0.0.0.0", "--port", "8081"]
