FROM node:20-alpine

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia apenas os arquivos de dependência para aproveitar cache
COPY package.json ./

# Instala as dependências do projeto Expo
RUN npm install

# Copia o restante do projeto
COPY . .

# Expõe a porta usada pelo Metro Bundler
EXPOSE 8081

# Inicia o servidor de desenvolvimento do Expo
CMD ["npx", "expo", "start", "--host", "0.0.0.0", "--port", "8081"]