spring.application.name=main
spring.profiles.active=dev
api.security.token.secret=${JWT_SECRET}
api.url.front=${URL_FRONT}
spring.email.host=${EMAIL_HOST}
spring.email.port=${EMAIL_PORT}
spring.email.username=${EMAIL_USERNAME}
spring.email.password=${EMAIL_PASSWORD}
spring.email.properties.mail.smtp.auth=true
spring.email.properties.mail.smtp.starttls.enable=true