spring.application.name=main
spring.profiles.active=dev
api.security.token.secret=${JWT_SECRET}
api.security.encryption.secret=${ENCRYPTION_SECRET}
api.security.encryption.salt=${ENCRYPTION_SALT}
api.url.front=${URL_FRONT}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true